export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_STARTED = "FETCH_TODOS_STARTED";
export const FETCH_TODOS_FINISHED = "FETCH_TODOS_FINISHED";
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
